<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e66ecf2d-e2c6-448c-97a1-c1f48ca3e556</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_see_all_details</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[11]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="Button__button__b_aG7\ Button__goToDetailPage__Wo80z\ Button__beacon__klioO\ ProductShowcaseActions__action-button__e1NFl\ Button__secondary__sMAVa\ Button__disableInternalPointerEvents__lSs9R"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'See all details')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>See all details</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>