<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>92cc1f55-bcb9-425b-a429-652d00c25a3e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_see_all_details</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[11]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="Button__button__b_aG7\ Button__goToDetailPage__Wo80z\ Button__beacon__klioO\ ProductShowcaseActions__action-button__e1NFl\ Button__secondary__sMAVa\ Button__disableInternalPointerEvents__lSs9R"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'See all details')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>See all details</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>