<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a0bc7c78-9cb8-4ebc-9c57-548ab87e3b6e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_tesla_coil_wireless_transmission_educati</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[41]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="_bXVsd_container_GMk6b\ sbx-desktop"] [class="a-color-base\ a-spacing-small\ a-link-normal\ _bXVsd_link_gJc5l\ _bXVsd_hidden_L-XDK"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Tesla Coil Wireless Transmission Education Model
            Tesla Coil Wireless Transmission Education Model')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Tesla Coil Wireless Transmission Education Model
        Tesla Coil Wireless Transmission Education Model</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>