<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d7c50108-4ace-40b1-835a-8d86050a3a84</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[6]/div[1]/div[1]/span[1]/div[1]/div[1]/div[2]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="s-widget-container\ s-spacing-small\ s-widget-container-height-small\ celwidget\ slot\=MAIN\ template\=SEARCH_RESULTS\ widgetId\=search-results_4"] [class="a-link-normal\ s-no-outline"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>