<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>90559b4b-ab44-468e-b279-2d329f440bd6</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[1]/div[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="s-widget-container\ s-spacing-small\ s-widget-container-height-small\ celwidget\ slot\=MAIN\ template\=SEARCH_RESULTS\ widgetId\=search-results_2"] [class="a-link-normal\ s-no-outline"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>