<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>02186d7c-ba10-466c-a646-49e81c571c5c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[1]/div[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="s-widget-container\ s-spacing-small\ s-widget-container-height-small\ celwidget\ slot\=MAIN\ template\=SEARCH_RESULTS\ widgetId\=search-results_27"] &gt; [class="rush-component\ s-expand-height"] [class="a-link-normal\ s-no-outline"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>