<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f46b5099-dda9-4eae-9616-a101db743c5a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[14]/div[1]/div[1]/span[1]/div[1]/div[1]/div[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="s-widget-container\ s-spacing-small\ s-widget-container-height-small\ celwidget\ slot\=MAIN\ template\=SEARCH_RESULTS\ widgetId\=search-results_33"] [class="a-link-normal\ s-no-outline"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>