<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9f1e3204-a184-499d-a6cf-1511a1ef7b6f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[40]/div[1]/div[1]/span[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="s-pagination-item\ s-pagination-button"]:nth-child(5)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>3</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>