<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0f235fe4-8888-4b53-90b6-eea0d9087f8f</elementGuidId>
    <imagePath></imagePath>
    <name>input_continue</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[2]/span[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="a-button-inner"] &gt; #continue</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'continue') and equals(@type,'submit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>continue</value>
        <webElementGuid>c60c37bc-d038-405d-ba51-a218361f6480</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>c60c37bc-d038-405d-ba51-a218361f6480</webElementGuid>
    </webElementProperties>
</WebElementEntity>