<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0d4b2aa0-b922-453f-bd8c-24027d5e15d3</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_electronics</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[11]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="treeitem"]:nth-child(11) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Electronics')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Electronics</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>