<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>315734db-750b-462f-9bfc-0b280da1b5d2</elementGuidId>
    <imagePath></imagePath>
    <name>input_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/span[1]/span[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#nudge-not-now-button [class="a-button-input"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>c60c37bc-d038-405d-ba51-a218361f6480</webElementGuid>
    </webElementProperties>
</WebElementEntity>