<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f29a6a3c-0060-4f2c-89cc-b23f41614985</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_a_autoid_11</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#a-autoid-11</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'a-autoid-11') and equals(@text,'Next page')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>a-autoid-11</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Next page</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>