<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>20f81ea8-fffe-4d74-874b-cbea5d31c70d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_go_to_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/span[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#sw-gtc [class="a-button-text"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Go to Cart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Go to Cart</value>
        <webElementGuid>c60c37bc-d038-405d-ba51-a218361f6480</webElementGuid>
    </webElementProperties>
</WebElementEntity>