<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>112d6adb-d5d0-460b-a657-f5dae446c1f2</elementGuidId>
    <imagePath></imagePath>
    <name>i_object_4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[5]/div[1]/div[2]/div[1]/div[1]/form[1]/div[2]/div[7]/div[4]/div[1]/div[1]/label[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="a-checkbox\ a-checkbox-fancy\ sc-item-check-checkbox-selector\ sc-list-item-checkbox\ a-hover-disable"] [class="a-icon\ a-icon-checkbox"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>