<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>141d40ea-8f14-468e-98e3-7338627350b8</elementGuidId>
    <imagePath></imagePath>
    <name>i_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[5]/div[1]/div[2]/div[1]/div[1]/form[1]/div[2]/div[3]/div[4]/div[1]/div[1]/label[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#sc-active-500b9b47-61be-49c2-aa46-99e8b5bb6dec [class="a-checkbox\ a-checkbox-fancy\ sc-item-check-checkbox-selector\ sc-list-item-checkbox"] [class="a-icon\ a-icon-checkbox"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>