<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>133c6600-560c-49c2-9877-087e9d535b67</elementGuidId>
    <imagePath></imagePath>
    <name>i_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[5]/div[1]/div[2]/div[1]/div[1]/form[1]/div[2]/div[8]/div[4]/div[1]/div[1]/label[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#sc-active-f1f4eaac-7701-4037-9d11-8341bf84ac48 [class="a-checkbox\ a-checkbox-fancy\ sc-item-check-checkbox-selector\ sc-list-item-checkbox"] [class="a-icon\ a-icon-checkbox"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>