<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>06c89a40-9d72-4019-a04a-76eff6cede41</elementGuidId>
    <imagePath></imagePath>
    <name>i_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[5]/div[1]/div[2]/div[1]/div[1]/form[1]/div[2]/div[6]/div[4]/div[1]/div[1]/label[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#sc-active-09fcad94-ad26-4c61-a20b-240656fdaaab [class="a-checkbox\ a-checkbox-fancy\ sc-item-check-checkbox-selector\ sc-list-item-checkbox"] [class="a-icon\ a-icon-checkbox"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>