<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c388d40b-c869-4512-b015-c3b8f13dafd8</elementGuidId>
    <imagePath></imagePath>
    <name>i_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[5]/div[1]/div[2]/div[1]/div[1]/form[1]/div[2]/div[5]/div[4]/div[1]/div[1]/label[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#sc-active-d7053f6f-56a4-46d8-b0be-e3d816adaaa3 [class="a-checkbox\ a-checkbox-fancy\ sc-item-check-checkbox-selector\ sc-list-item-checkbox"] [class="a-icon\ a-icon-checkbox"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>