<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c7774eff-6836-4f96-b20d-be16c529d23a</elementGuidId>
    <imagePath></imagePath>
    <name>input_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[5]/div[1]/div[2]/div[1]/div[1]/form[1]/div[2]/div[3]/div[4]/div[1]/div[1]/label[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="a-checkbox\ a-checkbox-fancy\ sc-item-check-checkbox-selector\ sc-list-item-checkbox\ a-hover-disable"] [type="checkbox"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>