<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>34d9f10f-14b3-4134-853a-4dfc5e812cd5</elementGuidId>
    <imagePath></imagePath>
    <name>button_a_autoid_11_announce</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[8]/div[3]/div[4]/div[35]/div[1]/div[1]/form[1]/div[2]/ul[1]/li[2]/span[1]/div[1]/span[1]/span[1]/span[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#a-autoid-11-announce</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'a-autoid-11-announce') and equals(@type,'button') and equals(@text,'2 Pounds
            
            $24.99
            
            ($0.78 / Ounce)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>a-autoid-11-announce</value>
        <webElementGuid>c60c37bc-d038-405d-ba51-a218361f6480</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>2 Pounds
        
        $24.99
        
        ($0.78 / Ounce)</value>
        <webElementGuid>c60c37bc-d038-405d-ba51-a218361f6480</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c60c37bc-d038-405d-ba51-a218361f6480</webElementGuid>
    </webElementProperties>
</WebElementEntity>