<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>469f6db1-84c8-425a-89e8-3c08e2239bfc</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_movies</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="bBPMYR\ CesUY3\ GoanCL"]:nth-child(1) [class="FMbLPy"]:nth-child(2) &gt; [class="q6Dbh8"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Movies')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Movies</value>
        <webElementGuid>930be66e-1671-4577-83ad-a9ac2342a0b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>