<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b03fc5b4-6b93-4d0b-8a72-e290a79ddaa2</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_kindle_ebooks</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[6]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav-a"]:nth-child(4)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Kindle eBooks')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Kindle eBooks</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>