<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4a50a596-b286-4353-be69-6cf68fd9b680</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_kindle_ebooks</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[6]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav-a"]:nth-child(4)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Kindle eBooks')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Kindle eBooks</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>