<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>41bd82a9-529e-46d7-ae70-e2b3531e33a6</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_kids</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[4]/div[1]/div[1]/ul[1]/li[9]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="jCJGNg"]:nth-child(9) &gt; [class="YHGNCb"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Kids')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Kids</value>
        <webElementGuid>930be66e-1671-4577-83ad-a9ac2342a0b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>