<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3dd10b7a-b0be-4ecd-b72f-f0d8277ecf2b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[7]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[2]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#sc-item-500b9b47-61be-49c2-aa46-99e8b5bb6dec &gt; [class="a-section\ a-spacing-none\ ewc-item-content\ ewc-item-update-content"] [class="a-link-normal\ sc-product-link"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>