<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c676044b-7fdf-4a7b-918e-cc4f08799b45</elementGuidId>
    <imagePath></imagePath>
    <name>button_proceedToCheckout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-checkout[1]/aw-wizard[1]/div[1]/aw-wizard-step[3]/app-address[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="container login-container"] [class="float-end"] &gt; [type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Proceed to checkout')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="proceed-3"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Proceed to checkout</value>
        <webElementGuid>7cc658a5-ba96-45a5-9cca-b2b1d32210ed</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>7cc658a5-ba96-45a5-9cca-b2b1d32210ed</webElementGuid>
    </webElementProperties>
</WebElementEntity>