<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2608d182-37ea-4507-9e88-a2fcef93d34e</elementGuidId>
    <imagePath></imagePath>
    <name>checkbox_categoryId1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[1]/fieldset[1]/div[2]/ul[1]/fieldset[1]/div[2]/label[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="checkbox"]:nth-child(3) [class="checkbox"]:nth-child(3) [type="checkbox"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'category_id') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="category-01HZ182NBAS0TG36KSCBKXFRHP"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>category_id</value>
        <webElementGuid>7c112377-20bf-483f-abf4-37b2468a1c66</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>7c112377-20bf-483f-abf4-37b2468a1c66</webElementGuid>
    </webElementProperties>
</WebElementEntity>