<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5c3292b3-4940-452e-9c4b-62b667d48a48</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nav_orders</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[1]/div[3]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#nav-orders</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'nav-orders') and equals(@text,'Returns
            &amp; Orders')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>nav-orders</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Returns
        &amp; Orders</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>