<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2f85cf58-e319-4e39-ad40-9af58d373c30</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nav_orders</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[1]/div[3]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#nav-orders</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'nav-orders') and equals(@text,'Returns
            &amp; Orders')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>nav-orders</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Returns
        &amp; Orders</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>