<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>060e5918-d5fc-4bc0-b8f9-c011d906e4d0</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_bike_panniers_rack_trunks_bike_pannier</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#CardInstanceMQyeVgfYWMH0RkynDhMQWQ [class="_cDEzb_missionQuadrant_1Y7U_"]:nth-child(4)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Bike panniers &amp; rack trunks
            Bike panniers &amp; ra…')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Bike panniers &amp; rack trunks
        Bike panniers &amp; ra…</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>