<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>65b9f99a-aedd-4c3b-baf2-bbe5c5f79c0b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_computer_tablets_computer_tablets</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#CardInstanceqPES1CilU0ruNUGXd9HLBA [class="_cDEzb_missionQuadrant_1Y7U_"]:nth-child(4)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Computer tablets
            Computer tablets')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Computer tablets
        Computer tablets</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>