<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9e2082d9-28cc-4ebe-8daa-052144a2acf3</elementGuidId>
    <imagePath></imagePath>
    <name>image_bulldozer</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[1]/div[2]/div[1]/div[1]/img[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="img-fluid rounded-end"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Bulldozer')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01HZKT1022B1X5HP013KD17R2E"] &gt;&gt; internal:role=img</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Bulldozer</value>
        <webElementGuid>7c3d298d-b560-4ca7-84a6-443a8dd61352</webElementGuid>
    </webElementProperties>
</WebElementEntity>