<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>76ec70e3-5eeb-4266-8eac-ae97b1f611d2</elementGuidId>
    <imagePath></imagePath>
    <name>input_quantityForDrawerTool</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-checkout[1]/aw-wizard[1]/div[1]/aw-wizard-step[1]/app-cart[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#quantity-01j0hxpyxy2tpkef24r98v7js5</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'quantity-01j0hxpyxy2tpkef24r98v7js5') and equals(@type,'number')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Quantity for Drawer Tool"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>quantity-01j0hxpyxy2tpkef24r98v7js5</value>
        <webElementGuid>73a99b12-c113-4ee2-8421-a5b28c90957e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>number</value>
        <webElementGuid>73a99b12-c113-4ee2-8421-a5b28c90957e</webElementGuid>
    </webElementProperties>
</WebElementEntity>