<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c649b524-cbb3-4d3e-b9f1-3ddf2a06e21c</elementGuidId>
    <imagePath></imagePath>
    <name>link_signIn</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-header[1]/nav[1]/div[1]/div[1]/ul[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav-item"]:nth-child(4) &gt; [class="nav-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Sign in')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="nav-sign-in"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign in</value>
        <webElementGuid>23bcfffa-b895-463e-9100-5d74eb035990</webElementGuid>
    </webElementProperties>
</WebElementEntity>