<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c5292f29-315f-415f-9d01-76e801095b2c</elementGuidId>
    <imagePath></imagePath>
    <name>link_woodSaw1218</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-category[1]/div[2]/div[2]/div[1]/a[8]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card ng-star-inserted"]:nth-child(8)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/product/01J0JFXY8P47B7MK4QRWGXS4XV') and equals(@text,'Wood Saw$12.18')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01J0JFXY8P47B7MK4QRWGXS4XV"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/product/01J0JFXY8P47B7MK4QRWGXS4XV</value>
        <webElementGuid>73a99b12-c113-4ee2-8421-a5b28c90957e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Wood Saw
        $12.18</value>
        <webElementGuid>73a99b12-c113-4ee2-8421-a5b28c90957e</webElementGuid>
    </webElementProperties>
</WebElementEntity>