<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>59ab938e-d926-491c-8347-18d27c822619</elementGuidId>
    <imagePath></imagePath>
    <name>link_safetyGoggles2426</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[8]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(8)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/product/01HZKT1013A0Z23NGTY2EVKG1C') and equals(@text,'Safety Goggles$24.26')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01HZKT1013A0Z23NGTY2EVKG1C"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/product/01HZKT1013A0Z23NGTY2EVKG1C</value>
        <webElementGuid>7c3d298d-b560-4ca7-84a6-443a8dd61352</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Safety Goggles
        $24.26</value>
        <webElementGuid>7c3d298d-b560-4ca7-84a6-443a8dd61352</webElementGuid>
    </webElementProperties>
</WebElementEntity>