<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a8a2d65e-d229-492d-a7d7-98efa46a7103</elementGuidId>
    <imagePath></imagePath>
    <name>link_drawerToolCabinet8955</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/product/01J0HX2848WY2N0K85EQPKDBAR') and equals(@text,'Drawer Tool Cabinet$89.55')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01J0HX2848WY2N0K85EQPKDBAR"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/product/01J0HX2848WY2N0K85EQPKDBAR</value>
        <webElementGuid>ab4102ea-8f43-44f9-b8b0-9c13d54e9bbe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Drawer Tool Cabinet
        $89.55</value>
        <webElementGuid>ab4102ea-8f43-44f9-b8b0-9c13d54e9bbe</webElementGuid>
    </webElementProperties>
</WebElementEntity>