<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5be68259-23d0-4c03-9cad-fe9fe92a51b2</elementGuidId>
    <imagePath></imagePath>
    <name>link_categoryPowerTools</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-header[1]/nav[1]/div[1]/div[1]/ul[1]/li[2]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown-menu show"] &gt; li:nth-child(2) &gt; [class="dropdown-item"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/category/power-tools') and equals(@text,'Power Tools')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="nav-power-tools"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/category/power-tools</value>
        <webElementGuid>a32204ce-3b35-4ae3-b56f-18784f34de75</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Power Tools</value>
        <webElementGuid>a32204ce-3b35-4ae3-b56f-18784f34de75</webElementGuid>
    </webElementProperties>
</WebElementEntity>