<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f1255f0e-45e1-4eb8-95c4-6f2dcd372737</elementGuidId>
    <imagePath></imagePath>
    <name>link_clawHammer</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[6]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(6)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Claw Hammer with Shock Reduction Grip$13.41')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01HY24E9MDK55TQCW102HEAYVT"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Claw Hammer with Shock Reduction Grip
        $13.41</value>
        <webElementGuid>23bcfffa-b895-463e-9100-5d74eb035990</webElementGuid>
    </webElementProperties>
</WebElementEntity>