<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3d4a829b-439c-44ae-a534-a0364cee0806</elementGuidId>
    <imagePath></imagePath>
    <name>link_sheetSander5848</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[8]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card ng-star-inserted"]:nth-child(8)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Sheet Sander$58.48')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01HZ182NF06WPW6XJ9NVEZHJYX"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sheet Sander
        $58.48</value>
        <webElementGuid>a32204ce-3b35-4ae3-b56f-18784f34de75</webElementGuid>
    </webElementProperties>
</WebElementEntity>