<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c09dcffc-46a7-4495-8d33-2407abdfa200</elementGuidId>
    <imagePath></imagePath>
    <name>link_tapeMeasure75m723</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[7]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card ng-star-inserted"]:nth-child(7)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/product/01J0HX283NHSJSMSWVW8W5AV18') and equals(@text,'Tape Measure 7.5m$7.23')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01J0HX283NHSJSMSWVW8W5AV18"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/product/01J0HX283NHSJSMSWVW8W5AV18</value>
        <webElementGuid>add4b005-e683-4267-9fc3-4e285f7ddd6e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Tape Measure 7.5m
        $7.23</value>
        <webElementGuid>add4b005-e683-4267-9fc3-4e285f7ddd6e</webElementGuid>
    </webElementProperties>
</WebElementEntity>