<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c126f700-9139-434d-840c-902eb18cc3ef</elementGuidId>
    <imagePath></imagePath>
    <name>link_navContact</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-header[1]/nav[1]/div[1]/div[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav-item"]:nth-child(3) &gt; [class="nav-link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/contact') and equals(@text,'Contact')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="nav-contact"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/contact</value>
        <webElementGuid>73a99b12-c113-4ee2-8421-a5b28c90957e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Contact</value>
        <webElementGuid>73a99b12-c113-4ee2-8421-a5b28c90957e</webElementGuid>
    </webElementProperties>
</WebElementEntity>