<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>506ffb5a-ab45-4a98-b5fa-0a808ecd006b</elementGuidId>
    <imagePath></imagePath>
    <name>link_thorHammer1114</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[9]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(9)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/product/01J0HX2835E1C7MNQ94FAJPR4J') and equals(@text,'Thor Hammer$11.14')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01J0HX2835E1C7MNQ94FAJPR4J"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/product/01J0HX2835E1C7MNQ94FAJPR4J</value>
        <webElementGuid>add4b005-e683-4267-9fc3-4e285f7ddd6e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Thor Hammer
        $11.14</value>
        <webElementGuid>add4b005-e683-4267-9fc3-4e285f7ddd6e</webElementGuid>
    </webElementProperties>
</WebElementEntity>