<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e50f44f0-c470-4cc2-9c2e-ab51ce8a4e8a</elementGuidId>
    <imagePath></imagePath>
    <name>link_product01J2G9F6Ehvmvgwwpgp7Kzy5N9</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/01J2G9F6EHVMVGWWPGP7KZY5N9') and equals(@text,'Bolt Cutters$48.41')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01J2G9F6EHVMVGWWPGP7KZY5N9"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/01J2G9F6EHVMVGWWPGP7KZY5N9</value>
        <webElementGuid>67b3957f-dcdb-4ad0-a744-39655b92aa3d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Bolt Cutters
        $48.41</value>
        <webElementGuid>67b3957f-dcdb-4ad0-a744-39655b92aa3d</webElementGuid>
    </webElementProperties>
</WebElementEntity>