<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a463c6a6-2a38-4348-9dc6-7b21754024fa</elementGuidId>
    <imagePath></imagePath>
    <name>link_handTools</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-header[1]/nav[1]/div[1]/div[1]/ul[1]/li[2]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown-menu show"] &gt; li:nth-child(1) &gt; [class="dropdown-item"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/category/hand-tools') and equals(@text,'Hand Tools')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="nav-hand-tools"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/category/hand-tools</value>
        <webElementGuid>73a99b12-c113-4ee2-8421-a5b28c90957e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Hand Tools</value>
        <webElementGuid>73a99b12-c113-4ee2-8421-a5b28c90957e</webElementGuid>
    </webElementProperties>
</WebElementEntity>