<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b31bcc6a-dcc9-4a3a-b588-b54359c65bca</elementGuidId>
    <imagePath></imagePath>
    <name>link_clawHammer1148</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(8)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/product/01J0HX2833FGCJG02T6V60SJ2D') and equals(@text,'Claw Hammer$11.48')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01J0HX2833FGCJG02T6V60SJ2D"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/product/01J0HX2833FGCJG02T6V60SJ2D</value>
        <webElementGuid>34d96539-83d2-4910-a9ab-b0faa56b6fe5</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Claw Hammer
        $11.48</value>
        <webElementGuid>34d96539-83d2-4910-a9ab-b0faa56b6fe5</webElementGuid>
    </webElementProperties>
</WebElementEntity>