<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>482ad75f-9e4f-48ca-97f3-7b6d875d929b</elementGuidId>
    <imagePath></imagePath>
    <name>link_slipJointPliers</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(5)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Slip Joint Pliers$9.17')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01HY24E9MAMQPAN2E731HVMTJC"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Slip Joint Pliers
        $9.17</value>
        <webElementGuid>23bcfffa-b895-463e-9100-5d74eb035990</webElementGuid>
    </webElementProperties>
</WebElementEntity>