<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a0ad740a-0f5a-4139-b1cd-de56f20481f0</elementGuidId>
    <imagePath></imagePath>
    <name>link_squareRuler1575</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[7]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(7)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/product/01HZKT10124C0SA4VY4B388YS9') and equals(@text,'Square Ruler$15.75')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01HZKT10124C0SA4VY4B388YS9"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/product/01HZKT10124C0SA4VY4B388YS9</value>
        <webElementGuid>a32204ce-3b35-4ae3-b56f-18784f34de75</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Square Ruler
        $15.75</value>
        <webElementGuid>a32204ce-3b35-4ae3-b56f-18784f34de75</webElementGuid>
    </webElementProperties>
</WebElementEntity>