<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c47cbbe9-d872-45e2-a616-f84939809198</elementGuidId>
    <imagePath></imagePath>
    <name>link_product01J0Hx282Vqm44Paz8Xswzgja2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="card"]:nth-child(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#/product/01J0JFXY9C28DRH74JCTVNSN7X') and equals(@text,'Super-thin Protection Gloves$38.45')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01J0JFXY9C28DRH74JCTVNSN7X"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#/product/01J0JFXY9C28DRH74JCTVNSN7X</value>
        <webElementGuid>bc41b86e-9b88-4c82-b928-76b41a82e7c8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Super-thin Protection Gloves
        $38.45</value>
        <webElementGuid>bc41b86e-9b88-4c82-b928-76b41a82e7c8</webElementGuid>
    </webElementProperties>
</WebElementEntity>