<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9fbaa23b-a12f-4641-82b7-f13bf6de4ca8</elementGuidId>
    <imagePath></imagePath>
    <name>span_ngxSlider3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-detail[1]/div[1]/div[2]/div[1]/ngx-slider[1]/span[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ngx-slider-span ngx-slider-bar-wrapper ngx-slider-full-bar"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ngx-slider &gt; span:nth-child(3)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>