<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8e20b2d1-da34-4123-916f-a69adb1c6632</elementGuidId>
    <imagePath></imagePath>
    <name>span_sliderBar</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[1]/div[1]/ngx-slider[1]/span[4]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ngx-slider-span ngx-slider-bar ngx-slider-selection"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span:nth-child(4) &gt; .ngx-slider-span</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>