<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>153c0a68-1c66-4a66-a8e5-ce2e491a4a53</elementGuidId>
    <imagePath></imagePath>
    <name>span_ngxSlider3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[1]/div[1]/ngx-slider[1]/span[3]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ngx-slider-span ngx-slider-bar-wrapper ngx-slider-full-bar"] &gt; [class="ngx-slider-span ngx-slider-bar"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span:nth-child(3) &gt; .ngx-slider-span</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>