<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0fd5c813-6482-4814-89ac-825f39821b44</elementGuidId>
    <imagePath></imagePath>
    <name>span_sliderMaxPointer</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[1]/div[1]/ngx-slider[1]/span[6]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ngx-slider-span ngx-slider-pointer ngx-slider-pointer-max ngx-slider-active"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=slider[name="ngx-slider-max"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>