<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>84a75522-5418-4452-bd77-8a69fe029618</elementGuidId>
    <imagePath></imagePath>
    <name>button_a_autoid_17_announce</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[4]/div[11]/div[4]/div[44]/div[1]/div[1]/form[1]/div[3]/ul[1]/li[1]/span[1]/div[1]/span[1]/span[1]/span[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#a-autoid-17-announce</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'a-autoid-17-announce') and equals(@type,'button') and equals(@text,'With 3 Months Free Kindle Unlimited')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>a-autoid-17-announce</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>With 3 Months Free Kindle Unlimited</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>