<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0c86f865-f337-4e8f-9188-09c9b6f5f006</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[5]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#detailpage-imageblock-player-7e3a0147-0770-47a2-81a6-6b33aa364670-container-element [class="vjs-progress-control\ vjs-control"] [class="vjs-mouse-display"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>