<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f4bbaf73-340e-49e2-9967-d166d81291ad</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="a-modal-scroller\ a-declarative"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>