<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>edf91053-94ea-4ef5-9468-e03e78b7d346</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_nav_item_signout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[3]/a[20]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#nav-item-signout</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'nav-item-signout') and equals(@text,'Sign Out')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>nav-item-signout</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign Out</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>