<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>af9ea129-5f18-46b2-a230-f268f2835f73</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_foeers_led_pixel_art_display_with_blueto</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[9]/div[13]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/ol[1]/li[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#sp_detail_B0CP1LMZ33 &gt; [class="a-link-normal"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'FOEERS LED Pixel Art Display with Bluetooth Speaker,16 * 16 Digital Picture Frame w...')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>FOEERS LED Pixel Art Display with Bluetooth Speaker,16 * 16 Digital Picture Frame w...</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>