<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7e3dc9e4-0629-4bc9-8223-0ef79c55b434</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_return_for_refund_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[5]/div[3]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/span[2]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#Return-for-refund_2</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'Return-for-refund_2') and equals(@text,'Return for refund')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>Return-for-refund_2</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Return for refund</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>