<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose your payment methodBank Trans_920188</name>
   <tag></tag>
   <elementGuidId>f8dbf378-51ac-4086-8c39-eb3709051db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-method</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='payment-method']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;payment-method&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>19170938-d7a4-4690-b797-e07e699a914e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>payment-method</value>
      <webElementGuid>ed498f37-0d77-45bb-8ba3-012ba96eb923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-method</value>
      <webElementGuid>18c45cc6-f09f-4fcb-a323-498e4d054b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>015081fd-48a5-452e-a59b-47e8ff252a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7c693fef-0226-410c-b74d-95bc6a3cc9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose your payment methodBank TransferCash on DeliveryCredit CardBuy Now Pay LaterGift Card</value>
      <webElementGuid>15d3258d-d0b8-4eae-b92d-bc1c7bedf77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-method&quot;)</value>
      <webElementGuid>edef9d8a-a3ee-47f9-80a6-bcc7c1249ee5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='payment-method']</value>
      <webElementGuid>9f89ff71-c802-4f64-90a5-57e5ac24f976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/following::select[1]</value>
      <webElementGuid>953f073f-7391-4e0c-83c5-c135ace52879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[2]/following::select[1]</value>
      <webElementGuid>185b1e3b-82de-45c8-88c2-9a387edcad19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::select[1]</value>
      <webElementGuid>0e30808e-8b6b-4c68-b278-9c3375b85efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GitHub repo'])[1]/preceding::select[1]</value>
      <webElementGuid>feeb2777-f6c3-49b0-a5a9-8af73f44dde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a5719dd9-6d88-4a19-b4b8-fa1b6e32bceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'payment-method' and (text() = 'Choose your payment methodBank TransferCash on DeliveryCredit CardBuy Now Pay LaterGift Card' or . = 'Choose your payment methodBank TransferCash on DeliveryCredit CardBuy Now Pay LaterGift Card')]</value>
      <webElementGuid>c4dcdbec-9d5a-420d-82dc-7e5335b75484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
