<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0227e51f-2a52-4627-a1fa-1b041a445f21</elementGuidId>
    <imagePath></imagePath>
    <name>button_left_arrow</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[4]/div[1]/section[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="yIoxDk\ WpAacf\ H1HVMS"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'left-arrow')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>left-arrow</value>
        <webElementGuid>930be66e-1671-4577-83ad-a9ac2342a0b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>