<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>92a20198-2403-43f1-a30f-5420eb32ba80</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_drama</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ol[1]/li[4]/div[1]/div[1]/ul[1]/li[5]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="_5-MZge\ _2-q9mI"] &gt; [class="jCJGNg"]:nth-child(5) &gt; [class="YHGNCb"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Drama')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Drama</value>
        <webElementGuid>930be66e-1671-4577-83ad-a9ac2342a0b9</webElementGuid>
    </webElementProperties>
</WebElementEntity>