<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9e1aef3a-044a-484a-9227-a81e50ec5fcd</elementGuidId>
    <imagePath></imagePath>
    <name>input_quantityForThorHammer</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-checkout[1]/aw-wizard[1]/div[1]/aw-wizard-step[1]/app-cart[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#quantity-01hzkvbdcqw4br5wkcxwjx6q8r</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'quantity-01hzkvbdcqw4br5wkcxwjx6q8r') and equals(@type,'number')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label="Quantity for Thor Hammer"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>quantity-01hzkvbdcqw4br5wkcxwjx6q8r</value>
        <webElementGuid>a32204ce-3b35-4ae3-b56f-18784f34de75</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>number</value>
        <webElementGuid>a32204ce-3b35-4ae3-b56f-18784f34de75</webElementGuid>
    </webElementProperties>
</WebElementEntity>