<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>50c0fa7c-791b-422b-bf8f-4a0c40ad3d5b</elementGuidId>
    <imagePath></imagePath>
    <name>link_table1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-checkout[1]/aw-wizard[1]/div[1]/aw-wizard-step[1]/app-cart[1]/div[1]/table[1]/tbody[1]/tr[2]/td[5]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-star-inserted"]:nth-child(2) &gt; [class="col-md-1 align-middle"] &gt; [class="btn btn-danger"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=table &gt;&gt; a &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>