<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0ed39f19-8547-4c54-820b-63adfeec7d45</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_the_swinging_sticks_kinetic_energy_sculp</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[8]/div[13]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/ol[1]/li[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#sp_detail_thematic-highly_rated_B0971SY1JS &gt; [class="a-link-normal"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'The Swinging Sticks Kinetic Energy Sculpture - Desktop Toy Version (White/Silver)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>The Swinging Sticks Kinetic Energy Sculpture - Desktop Toy Version (White/Silver)</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>