<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>25d56bec-e57f-4418-aa28-0321f22e3db9</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_returnreasondropdown_9</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/ul[1]/li[10]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#returnReasonDropdown_9</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'returnReasonDropdown_9') and equals(@text,'Accidental Purchase')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>returnReasonDropdown_9</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Accidental Purchase</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>