<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d96deb6f-3bfa-4ec8-8857-305697c8275f</elementGuidId>
    <imagePath></imagePath>
    <name>input_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#returnSubmitBtn [class="a-button-input"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>