<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b9f5b9e3-8175-45e6-9e61-204b215eb88d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_ap_account_fixup_phone_skip_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[5]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#ap-account-fixup-phone-skip-link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'ap-account-fixup-phone-skip-link') and equals(@text,'Not now')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>ap-account-fixup-phone-skip-link</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Not now</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>