<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>caea2cae-a5c2-45a6-8d29-02713681e966</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_books</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[4]/div[2]/div[2]/div[1]/a[8]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="nav-a\ \ "]:nth-child(9)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Books')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Books</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>