<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>91100b8a-8ad8-4299-8709-e087853cf246</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_a_autoid_18</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[8]/div[12]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#a-autoid-18</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'a-autoid-18') and equals(@text,'Next page')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>a-autoid-18</value>
        <webElementGuid>c60c37bc-d038-405d-ba51-a218361f6480</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Next page</value>
        <webElementGuid>c60c37bc-d038-405d-ba51-a218361f6480</webElementGuid>
    </webElementProperties>
</WebElementEntity>