<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>75a32eaf-6229-4a0c-bbaa-3d6be2adf4ed</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_digital_orders</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/section[1]/div[1]/div[3]/ul[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="page-tabs__tab"]:nth-child(4) &gt; [class="a-link-normal"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Digital Orders')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Digital Orders</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>