<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>51455a61-bb8f-47b1-b0af-ccffe1f2083c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_digital_orders</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/section[1]/div[1]/div[3]/ul[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="page-tabs__tab"]:nth-child(4) &gt; [class="a-link-normal"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Digital Orders')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Digital Orders</value>
        <webElementGuid>6c1f14cf-11a3-43a1-9af7-09503300c86d</webElementGuid>
    </webElementProperties>
</WebElementEntity>