<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ff68e416-2d28-48e8-9ffb-fdb5db8bf35d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_book_cover_image_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#book-view-wrapper-B071CTK28D [class="azCNjaMDD4dQ4cwob9rri\ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'book-cover-image-link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>book-cover-image-link</value>
        <webElementGuid>e903b011-0125-4e5b-ace9-0c1a278bf70b</webElementGuid>
    </webElementProperties>
</WebElementEntity>